### PR TITLE
Update

### PR DESCRIPTION
**Pull request by larsenv**
Added reminder commands, other minor changes...

### CODE REVIEW

**Comment by larsenv** [comment]
That was rude of you. /s

The warnings are restricted because I don't want some asshole that pretends to be staff to start using them in chat like they are a staff member.

The indent thing is Atom's fault.

**Comment by spotlightishere** [comment]
You can always fix the indent yourself. And so what, people should be able to see the rules too? See also, https://github.com/916253/Kurisu/blob/master/addons/rules.py

(the bot used in Nintendo Homebrew)

**Comment by larsenv** [comment]
Go fix it yourself and I'll do it next time.

**Comment by ArtutoGamer** [comment]
Lmao XD

**Comment by spotlightishere** [comment]
Sorry, no can do, it's your PR.

**Comment by spotlightishere** [comment]
As the user said they're not gonna fix it, I'll just save all 6 people watching this project some time and close it.

**Pull request closed without merging**
